[package]
name = "Q3"
version = "0.1.0"
authors = ["salmanrafiq <salmanrafiq5839@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calculator = {path ="../calculator"}
